name: flutter_zimpligital_siravit
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  infinite_scroll_pagination: ^4.0.0
  json_annotation: ^4.8.1
  just_audio: ^0.9.36
  logger: ^2.0.2+1
  lottie: ^2.7.0
  percent_indicator: ^4.2.3
  retrofit: ^4.0.3

dev_dependencies:
  build_runner: ^2.4.7

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6

flutter:
  uses-material-design: true

  assets:
    - ./assets/lotties/

  fonts:
    - family: Promp
      fonts:
        - asset: fonts/Prompt-ExtraLight.ttf
          weight: 200
        - asset: fonts/Prompt-Light.ttf
          weight: 300
        - asset: fonts/Prompt-Regular.ttf
        - asset: fonts/Prompt-Medium.ttf
          weight: 500
        - asset: fonts/Prompt-SemiBold.ttf
          weight: 600
        - asset: fonts/Prompt-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/core/gen
  integrations:
    lottie: true
